# fly.toml file generated for floral-wave-1444 on 2023-02-14T20:09:42+01:00

app = "floral-wave-1444"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builtin = "python"

[[mounts]]
  destination = "/data"
  source = "cardgames_data"

[env]

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 100
    soft_limit = 80
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 5
    timeout = "2s"
