# See PEP 518 for the spec of this file
# https://www.python.org/dev/peps/pep-0518/

[tool.black]
# See https://github.com/ambv/black/blob/master/pyproject.toml
line-length = 88
target_version = ["py310"]

[tool.isort]
profile = "black"
balanced_wrapping = true
combine_as_imports = true
default_section = "THIRDPARTY"
indent = "    "
known_first_party = []

[tool.mypy]
check_untyped_defs = true
disallow_untyped_calls = false
disallow_untyped_defs = false
ignore_missing_imports = true
python_version = "3.10"
strict_optional = false
warn_redundant_casts = true
warn_unused_ignores = true
show_error_codes = true
