---
name: Run Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          # currently deployed using py3.8
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort pytest mypy
      - name: Run tests with pytest
        run: python -m pytest
      - name: Check black
        run: black --check app/
      - name: Check isort
        run: isort  --check-only --diff app
      - name: run mypy (not yet required to pass)
        run: mypy app --install-types --non-interactive || true
